### ISSUE TITLE
Dockerfileの管理について

### ISSUE THREAD

**Issue by Amano123** [Amano123/starfish_system#2]
Docker-composeで複数コンテナを管理する。
Dockerfileの管理をどうするか、ここで議論する。

**Comment by Amano123** [comment]
TensorflowとPyTorchのDockerfileを別に作成する際に

```
.
├── docker-compose.yml
├── dockerfile(tensorflow)
├── dockerfile(pytorch)
```
こんな感じで管理はしたくないねえ

**Comment by Amano123** [comment]
TensorflowとPyTorchのDockerfileを別に作成する際に
```
.
├── docker-compose.yml
├── Tensorflow
│   └── dockerfile
├── pytorch
│   └── dockerfile

```
こうする？

**Comment by HirotoYano** [comment]
> TensorflowとPyTorchのDockerfileを別に作成する際に
> 
> ```
> .
> ├── docker-compose.yml
> ├── Tensorflow
> │   └── dockerfile
> ├── pytorch
> │   └── dockerfile
> ```
> 
> こうする？

この構成にしますか

**Comment by Amano123** [comment]
了解！実装するンゴ

**Comment by Amano123** [comment]
この構成で行こうか、また問題があればOpenにするんでそのときによろしくです。
